import React from 'react'
import Source from '@/code/Source.jsx'
import pages from '@/snippets/config/pages.jsx?raw'
import matchPagesPrefix from '@/snippets/config/matchPagesPrefix.jsx?raw'
import matchPageSuffix from '@/snippets/config/matchPageSuffix.jsx?raw'
import Link from '@/ui/Link.jsx'
import { Warning } from '@abw/badger-react-ui'

const Pages = () =>
  <div>
    <h1 className="font-mono">pages</h1>
    <p>
      The <code>pages</code> option is passed to the <code>SiteProvider</code>{' '}
      component as an object mapping paths to component for all the pages in
      the site.  Unless you know what you&apos;re doing, this should normally
      be generated by calling the{' '}
      <Link href="https://vitejs.dev/guide/features.html#glob-import" targetBlank code="import.meta.glob"/>{' '}
      function provided by Vite.
    </p>
    <p>
      This will find and load all of the pages under the <code>./pages/</code>{' '}
      directory that have a <code>.js</code>, <code>.jsx</code>, <code>.ts</code>{' '}
      or <code>.tsx</code> extension.
    </p>
    <Source
      code={pages}
      language="jsx"
    />

    <h2 className="font-mono mar-t-8">matchPagesPrefix</h2>
    <p>
      If your pages aren&apos;t under the <code>./pages/</code> directory
      then you should also pass the <code>matchPagesPrefix</code> option
      to the <Link to="/configuration/site-provider" code="SiteProvider"/>{' '}
      module, defined as a regular expression to match the prefix.  The default
      value is <code>/^[./]*pages/</code>
    </p>
    <Source
      code={matchPagesPrefix}
      language="jsx"
      highlightLines="2,9"
    />

    <h2 className="font-mono mar-t-8">matchPageSuffix</h2>
    <p>
      If you want to match pages that have different file extensions
      then you should also pass the <code>matchPageSuffix</code> option
      to the <Link to="/configuration/site-provider" code="SiteProvider"/>{' '}
      module, defined as a regular expression to match the suffix.  The default
      value is <code>/\.[jt]sx?$/</code>
    </p>
    <Source
      code={matchPageSuffix}
      language="jsx"
      highlightLines="2,9"
    />
    <Warning title="Important Note" className="mar-t-4" border icon="exclamation">
      Note that the pattern passed to the <code>import.meta.glob</code> function
      is expanded using <Link href="https://github.com/mrmlnc/fast-glob#pattern-syntax" code="fast-glob" targetBlank/>{' '}
      whereas <code>matchPagesPrefix</code> and <code>matchPageSuffix</code> are
      JS regular expressions.  The syntax is different.
    </Warning>
  </div>

export default Pages